---
- name: here comes the playbook for the building the docker image to intialize the cluster
  hosts: all
  become: true
  remote_user: mukunth
  tasks:
    - name: here comes the second block to start the docker service
      service:
        name: docker
        state: started
        ignore_errors: yes
    - name: here comes comes the third block to implement the docker-build
      command: docker build . -t mukuntharya2022/myapp:${DOCKER_TAG} 
      args:
        chdir: /home/mukunth/go
    - name: here we push docker images to docker repo
      command: docker push mukuntharya2022/myapp:${DOCKER_TAG}
...
          
         
    
