---
- name: here comes the playbook for the building the docker image to intialize the cluster
  hosts: all
  become: true
  remote_user: mukunth
  tasks:
    - name: here we install the docker in this playbook
      apt:
        name: docker.io
        state: present
    - name: here comes the second block to start the docker service
      service:
        name: docker
        state: started
    
...
          
         
    
