---
- name: here comes the playbook for installation for minikube inside the cluster
  hosts: myinternal
  become: true
  remote_user: mukunth
  tasks:
    - name: here we install the basic packages needed to install the app
      apt:
        name: curl  
        state: present
    - name: here we install virtual box hypervisor
      apt:
        name: virtualbox
        state: present
   
    - name: here we copy the minikube file to following repo
      copy:
        src: /home/mukunth/minikube-linux-amd64
        dest: /usr/local/bin/minikube
    - name: here we set the execution permission
      command: chmod 0777 /usr/local/bin/minikube
    
        
    - name: here we install the kubectl in the playbook
      command: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - name: herewe give permission to execute
      command: chmod 777 ./kubectl
    - name: here we set the command
      command: mv ./kubectl /usr/local/bin/kubectl 
        
       
...
