---
- name: here comes the files to deploy cluster
  hosts: all
  remote_user: mukunth
  become: true
  tasks:
    - name: here we install contrack tool
      apt:
        name: conntrack
        state: present
    - name: here we start the kunernetescluster
      command: sudo minikube start --driver=none
    
    
...
    
