---
- name: here comes the files to deploy cluster
  hosts: all
  remote_user: mukunth
  become: true
  tasks:
    - name: here we start the kunernetescluster
      command: minikube start --driver=none
    - name: here comes the first play to deploy pod
      command: kubectl create -f deployment.yaml
      args:
        chdir: /home/mukunth/ansible
    - name: here we dploy the services
      command: kubectl create-f services.yaml
      args:
        chdir: /home/mukunth/ansible
...
    
